-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3308
-- Generation Time: Oct 12, 2018 at 10:37 AM
-- Server version: 5.7.23
-- PHP Version: 7.2.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ngb_ebanking2`
--

-- --------------------------------------------------------

--
-- Table structure for table `account`
--

DROP TABLE IF EXISTS `account`;
CREATE TABLE IF NOT EXISTS `account` (
  `acc_num` varchar(7) NOT NULL COMMENT 'bank account number',
  `email` varchar(30) NOT NULL COMMENT 'emaiil address of the customer',
  PRIMARY KEY (`acc_num`),
  KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='this table stores the banking information of the customer';

-- --------------------------------------------------------

--
-- Table structure for table `bill_pay`
--

DROP TABLE IF EXISTS `bill_pay`;
CREATE TABLE IF NOT EXISTS `bill_pay` (
  `trans_id` int(11) NOT NULL COMMENT 'Unique identifier of transaction',
  `serv_prov` varchar(12) NOT NULL COMMENT 'name of service provider',
  PRIMARY KEY (`trans_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Stores bill payment specific information';

-- --------------------------------------------------------

--
-- Table structure for table `customer`
--

DROP TABLE IF EXISTS `customer`;
CREATE TABLE IF NOT EXISTS `customer` (
  `email` varchar(30) NOT NULL COMMENT 'Customer email address',
  `Photo` text NOT NULL COMMENT 'Stores path to customer image',
  PRIMARY KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='table stores the photos of customers';

-- --------------------------------------------------------

--
-- Table structure for table `message`
--

DROP TABLE IF EXISTS `message`;
CREATE TABLE IF NOT EXISTS `message` (
  `mess_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'message id is autogenerated',
  `email` varchar(30) NOT NULL COMMENT 'email address of customer who left the message',
  `date` date NOT NULL COMMENT 'date stamp of message',
  `time` time NOT NULL COMMENT 'time stamp of messge',
  `type` varchar(5) NOT NULL COMMENT 'type of query',
  `mess_body` text NOT NULL COMMENT 'contents of message',
  PRIMARY KEY (`mess_id`),
  KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='message table stores message info left for customer service';

-- --------------------------------------------------------

--
-- Table structure for table `transactions`
--

DROP TABLE IF EXISTS `transactions`;
CREATE TABLE IF NOT EXISTS `transactions` (
  `trans_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'unique identifier of each transaction',
  `trans_type` enum('DEPO=1','TRANS=2','BILL=3','') NOT NULL COMMENT 'code that identifies each type of transaction',
  `date` date NOT NULL COMMENT 'date of transaction',
  `time` time NOT NULL COMMENT 'time of transaction',
  `amount` decimal(10,0) NOT NULL COMMENT 'cash value of transaction',
  `descrip` varchar(80) NOT NULL COMMENT 'details of transaction',
  `acc_num` varchar(7) NOT NULL COMMENT 'transaction initiator''s account number',
  PRIMARY KEY (`trans_id`),
  KEY `acc_num` (`acc_num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Table stores information on customer transactions';

-- --------------------------------------------------------

--
-- Table structure for table `transfer`
--

DROP TABLE IF EXISTS `transfer`;
CREATE TABLE IF NOT EXISTS `transfer` (
  `trans_id` int(11) NOT NULL COMMENT 'unique identifier of each transaction',
  `rec_email` varchar(40) NOT NULL COMMENT 'reciever''s email address',
  PRIMARY KEY (`trans_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Table stores all transfer specific information';

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `email` varchar(40) NOT NULL COMMENT 'Email address of user',
  `FName` varchar(20) NOT NULL COMMENT 'First name of user',
  `LName` varchar(30) NOT NULL COMMENT 'Last name of user',
  `Type` binary(1) NOT NULL COMMENT 'User can be a manager or a customer, 1=manager, 0=customer',
  PRIMARY KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='User table which storees information on all users ';

--
-- Constraints for dumped tables
--

--
-- Constraints for table `account`
--
ALTER TABLE `account`
  ADD CONSTRAINT `fk_bank` FOREIGN KEY (`email`) REFERENCES `customer` (`email`);

--
-- Constraints for table `bill_pay`
--
ALTER TABLE `bill_pay`
  ADD CONSTRAINT `fk_bill_pay` FOREIGN KEY (`trans_id`) REFERENCES `transactions` (`trans_id`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `customer`
--
ALTER TABLE `customer`
  ADD CONSTRAINT `fk_customer` FOREIGN KEY (`email`) REFERENCES `user` (`email`);

--
-- Constraints for table `message`
--
ALTER TABLE `message`
  ADD CONSTRAINT `fk_message` FOREIGN KEY (`email`) REFERENCES `customer` (`email`);

--
-- Constraints for table `transactions`
--
ALTER TABLE `transactions`
  ADD CONSTRAINT `fk_acc_transac` FOREIGN KEY (`acc_num`) REFERENCES `account` (`acc_num`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `transfer`
--
ALTER TABLE `transfer`
  ADD CONSTRAINT `fk_transfer` FOREIGN KEY (`trans_id`) REFERENCES `transactions` (`trans_id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
